function FailureAnalysis({ result }) {

    return (

        <section
            className="analysisSection fadeUp"
            id="results"
        >

            <div className="analysisHeader">

                <span className="panelBadge">

                    AI DEBUGGER

                </span>

                <h2>

                    Failure Analysis

                </h2>

                <p>

                    Detailed runtime diagnostics generated by the
                    AI Debugger Agent.

                </p>

            </div>

            <div className="analysisGrid">

                <div className="analysisCard">

                    <h3>

                        Failed File

                    </h3>

                    <div className="analysisValue">

                        {

                            result.failed_file ||

                            "No failure detected."

                        }

                    </div>

                </div>

                <div className="analysisCard">

                    <h3>

                        Debugger Analysis

                    </h3>

                    <pre className="analysisCode">

                        {

                            result.debug_analysis ||

                            "No analysis available."

                        }

                    </pre>

                </div>

            </div>

        </section>

    );

}

export default FailureAnalysis;